"""booking flight number

Revision ID: 165a12b47eda
Revises: 1b3f7a150a83
Create Date: 2026-07-24 15:35:06.829539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '165a12b47eda'
down_revision: Union[str, None] = '1b3f7a150a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('flight_number')

    # ### end Alembic commands ###
