"""bag edit revokes

Revision ID: 1a0a99dee99b
Revises: 1baaa8535b7a
Create Date: 2026-07-30 23:44:48.700396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a0a99dee99b'
down_revision: Union[str, None] = '1baaa8535b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_edit_revokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_traveler_id', sa.Integer(), nullable=False),
    sa.Column('editor_traveler_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['editor_traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_traveler_id', 'editor_traveler_id')
    )
    with op.batch_alter_table('bag_edit_revokes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bag_edit_revokes_editor_traveler_id'), ['editor_traveler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bag_edit_revokes_owner_traveler_id'), ['owner_traveler_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag_edit_revokes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bag_edit_revokes_owner_traveler_id'))
        batch_op.drop_index(batch_op.f('ix_bag_edit_revokes_editor_traveler_id'))

    op.drop_table('bag_edit_revokes')
    # ### end Alembic commands ###
