"""booking segments

Revision ID: 1baaa8535b7a
Revises: b9e2d7c14a83
Create Date: 2026-07-30 20:19:37.854374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1baaa8535b7a'
down_revision: Union[str, None] = 'b9e2d7c14a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('departure_dt', sa.DateTime(), nullable=True),
    sa.Column('arrival_dt', sa.DateTime(), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_segments_booking_id'), ['booking_id'], unique=False)

    # backfill: cada transporte existente con algún dato de ruta/fecha pasa a
    # tener su único tramo (position 0); el flight_number se muda al tramo
    op.execute(
        "INSERT INTO booking_segments "
        "(booking_id, position, origin, destination, departure_dt, arrival_dt, flight_number) "
        "SELECT id, 0, origin, destination, start_dt, end_dt, flight_number "
        "FROM bookings WHERE type IN ('flight', 'train', 'bus', 'ferry') "
        "AND (origin IS NOT NULL OR destination IS NOT NULL OR start_dt IS NOT NULL"
        " OR end_dt IS NOT NULL OR flight_number IS NOT NULL)"
    )
    op.execute(
        "UPDATE bookings SET flight_number = NULL "
        "WHERE id IN (SELECT booking_id FROM booking_segments)"
    )


def downgrade() -> None:
    # best-effort: el primer tramo vuelve a las columnas planas (los demás se pierden)
    op.execute(
        "UPDATE bookings SET flight_number = ("
        "SELECT s.flight_number FROM booking_segments s "
        "WHERE s.booking_id = bookings.id AND s.position = 0"
        ") WHERE flight_number IS NULL AND id IN (SELECT booking_id FROM booking_segments)"
    )
    with op.batch_alter_table('booking_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_segments_booking_id'))

    op.drop_table('booking_segments')
