"""common wallet payer

Revision ID: 376c63a63d01
Revises: f7fac4bfc35b
Create Date: 2026-07-24 12:28:09.489459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '376c63a63d01'
down_revision: Union[str, None] = 'f7fac4bfc35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by_common', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('paid_by_common')

    # ### end Alembic commands ###
