"""trip links

Revision ID: 38c6de3f94ac
Revises: 1a0a99dee99b
Create Date: 2026-09-15 18:14:16.883130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38c6de3f94ac'
down_revision: Union[str, None] = '1a0a99dee99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_groups_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['link_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_links_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_links_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_links_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_links_group_id'))

    op.drop_table('trip_links')
    with op.batch_alter_table('link_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_groups_trip_id'))

    op.drop_table('link_groups')
    # ### end Alembic commands ###
