"""packing template item position

Revision ID: 39cd39d4c209
Revises: 307db45f83d2
Create Date: 2026-09-23 18:28:48.643408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39cd39d4c209'
down_revision: Union[str, None] = '307db45f83d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_template_items', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
