"""day journals

Revision ID: 52b29335337b
Revises: 165a12b47eda
Create Date: 2026-07-25 17:23:54.500811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52b29335337b'
down_revision: Union[str, None] = '165a12b47eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('photo_image', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'day')
    )
    with op.batch_alter_table('day_journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_journals_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_journals_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_journals_trip_id'))
        batch_op.drop_index(batch_op.f('ix_day_journals_day'))

    op.drop_table('day_journals')
    # ### end Alembic commands ###
