"""expense in_stats flag

Revision ID: 6860e81b3c51
Revises: 70eae617dd0e
Create Date: 2026-09-22 19:20:17.649158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6860e81b3c51'
down_revision: Union[str, None] = '70eae617dd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stats', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('in_stats')

    # ### end Alembic commands ###
