"""world place photo (postal)

Revision ID: 6adb54e34b16
Revises: f498079f16d0
Create Date: 2026-07-27 18:38:49.642881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6adb54e34b16'
down_revision: Union[str, None] = 'f498079f16d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.drop_column('photo_image')

    # ### end Alembic commands ###
