"""world place region

Revision ID: 70cdf16f12c9
Revises: 6adb54e34b16
Create Date: 2026-07-28 14:15:25.487839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70cdf16f12c9'
down_revision: Union[str, None] = '6adb54e34b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_code', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_world_places_region_code'), ['region_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_places_region_code'))
        batch_op.drop_column('region_code')

    # ### end Alembic commands ###
