"""packing item quantity

Revision ID: 70eae617dd0e
Revises: bbd549ae2126
Create Date: 2026-09-22 19:10:09.937459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70eae617dd0e'
down_revision: Union[str, None] = 'bbd549ae2126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('packing_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_template_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('packing_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
