"""link icons and images

Revision ID: 7d5984405bd1
Revises: 38c6de3f94ac
Create Date: 2026-09-15 18:39:24.542435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d5984405bd1'
down_revision: Union[str, None] = '38c6de3f94ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=40), nullable=True))

    with op.batch_alter_table('trip_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_links', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('link_groups', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
