"""checklist url

Revision ID: 7dea00d95e10
Revises: 7ee5159f45d6
Create Date: 2026-07-27 18:01:51.202284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7dea00d95e10'
down_revision: Union[str, None] = '7ee5159f45d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
