"""expense paid flag

Revision ID: 9e7c537ea87c
Revises: 7d5984405bd1
Create Date: 2026-09-15 19:59:14.146187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e7c537ea87c'
down_revision: Union[str, None] = '7d5984405bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
