"""trip secondary currency

Revision ID: bbd549ae2126
Revises: 9e7c537ea87c
Create Date: 2026-09-15 20:55:47.241504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbd549ae2126'
down_revision: Union[str, None] = '9e7c537ea87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('secondary_currency')

    # ### end Alembic commands ###
