"""image focus

Encuadre de cada imagen recortada (portada de viaje, avatar, postal del día y
postal del mapa): dos floats 0-1 que acaban siendo el `object-position` del
recorte. 0,5/0,5 = centrada, que es exactamente lo que hacía el navegador antes
de que se pudiera mover, así que lo que ya existe no cambia de aspecto.

Revision ID: c1bf988e03a5
Revises: 8f0ae2923719
Create Date: 2026-07-28 22:48:37.651693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1bf988e03a5'
down_revision: Union[str, None] = '8f0ae2923719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_focus_x', sa.Float(), server_default='0.5', nullable=False))
        batch_op.add_column(sa.Column('photo_focus_y', sa.Float(), server_default='0.5', nullable=False))

    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_focus_x', sa.Float(), server_default='0.5', nullable=False))
        batch_op.add_column(sa.Column('avatar_focus_y', sa.Float(), server_default='0.5', nullable=False))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_focus_x', sa.Float(), server_default='0.5', nullable=False))
        batch_op.add_column(sa.Column('cover_focus_y', sa.Float(), server_default='0.5', nullable=False))

    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_focus_x', sa.Float(), server_default='0.5', nullable=False))
        batch_op.add_column(sa.Column('photo_focus_y', sa.Float(), server_default='0.5', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.drop_column('photo_focus_y')
        batch_op.drop_column('photo_focus_x')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('cover_focus_y')
        batch_op.drop_column('cover_focus_x')

    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('avatar_focus_y')
        batch_op.drop_column('avatar_focus_x')

    with op.batch_alter_table('day_journals', schema=None) as batch_op:
        batch_op.drop_column('photo_focus_y')
        batch_op.drop_column('photo_focus_x')

    # ### end Alembic commands ###
