"""family documents

Revision ID: eaec061fddea
Revises: 39cd39d4c209
Create Date: 2026-09-25 15:22:02.212973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eaec061fddea'
down_revision: Union[str, None] = '39cd39d4c209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('stored_name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_traveler_id'), ['traveler_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_traveler_id'))
        batch_op.drop_index(batch_op.f('ix_documents_family_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###
