"""world place visited date

Revision ID: f498079f16d0
Revises: 7dea00d95e10
Create Date: 2026-07-27 18:22:06.118557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f498079f16d0'
down_revision: Union[str, None] = '7dea00d95e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visited_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_places', schema=None) as batch_op:
        batch_op.drop_column('visited_month')
        batch_op.drop_column('visited_year')

    # ### end Alembic commands ###
