"""expense splitting

Revision ID: f7fac4bfc35b
Revises: f7a8b9c0d1e2
Create Date: 2026-07-24 12:04:02.555465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7fac4bfc35b'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'traveler_id')
    )
    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_shares_expense_id'), ['expense_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_mode', sa.String(length=10), server_default='equal', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('split_mode')

    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_shares_expense_id'))

    op.drop_table('expense_shares')
    # ### end Alembic commands ###
