services:
  turtletrips:
    container_name: turtletrips
    image: ghcr.io/turtletrips/turtletrips:latest
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    environment:
      - TT_DEFAULT_CURRENCY=EUR
      # - TT_NOMINATIM_URL=https://nominatim.openstreetmap.org
      # - TT_RATES_URL=https://api.frankfurter.dev/v1
    restart: unless-stopped
