import { currentLocale, intlLocale } from './i18n'

export interface Country {
  code: string // ISO 3166-1 alpha-2
  es: string // nombre en español (UI)
  en: string // nombre en inglés (búsqueda de imagen en Wikivoyage)
}

/** Bandera emoji a partir del código ISO alpha-2 */
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)))
}

export const COUNTRIES: Country[] = [
  { code: 'AF', es: 'Afganistán', en: 'Afghanistan' },
  { code: 'AL', es: 'Albania', en: 'Albania' },
  { code: 'DE', es: 'Alemania', en: 'Germany' },
  { code: 'AD', es: 'Andorra', en: 'Andorra' },
  { code: 'AO', es: 'Angola', en: 'Angola' },
  { code: 'AG', es: 'Antigua y Barbuda', en: 'Antigua and Barbuda' },
  { code: 'SA', es: 'Arabia Saudí', en: 'Saudi Arabia' },
  { code: 'DZ', es: 'Argelia', en: 'Algeria' },
  { code: 'AR', es: 'Argentina', en: 'Argentina' },
  { code: 'AM', es: 'Armenia', en: 'Armenia' },
  { code: 'AU', es: 'Australia', en: 'Australia' },
  { code: 'AT', es: 'Austria', en: 'Austria' },
  { code: 'AZ', es: 'Azerbaiyán', en: 'Azerbaijan' },
  { code: 'BS', es: 'Bahamas', en: 'Bahamas' },
  { code: 'BD', es: 'Bangladés', en: 'Bangladesh' },
  { code: 'BB', es: 'Barbados', en: 'Barbados' },
  { code: 'BH', es: 'Baréin', en: 'Bahrain' },
  { code: 'BE', es: 'Bélgica', en: 'Belgium' },
  { code: 'BZ', es: 'Belice', en: 'Belize' },
  { code: 'BJ', es: 'Benín', en: 'Benin' },
  { code: 'BY', es: 'Bielorrusia', en: 'Belarus' },
  { code: 'BO', es: 'Bolivia', en: 'Bolivia' },
  { code: 'BA', es: 'Bosnia y Herzegovina', en: 'Bosnia and Herzegovina' },
  { code: 'BW', es: 'Botsuana', en: 'Botswana' },
  { code: 'BR', es: 'Brasil', en: 'Brazil' },
  { code: 'BN', es: 'Brunéi', en: 'Brunei' },
  { code: 'BG', es: 'Bulgaria', en: 'Bulgaria' },
  { code: 'BF', es: 'Burkina Faso', en: 'Burkina Faso' },
  { code: 'BI', es: 'Burundi', en: 'Burundi' },
  { code: 'BT', es: 'Bután', en: 'Bhutan' },
  { code: 'CV', es: 'Cabo Verde', en: 'Cape Verde' },
  { code: 'KH', es: 'Camboya', en: 'Cambodia' },
  { code: 'CM', es: 'Camerún', en: 'Cameroon' },
  { code: 'CA', es: 'Canadá', en: 'Canada' },
  { code: 'QA', es: 'Catar', en: 'Qatar' },
  { code: 'TD', es: 'Chad', en: 'Chad' },
  { code: 'CL', es: 'Chile', en: 'Chile' },
  { code: 'CN', es: 'China', en: 'China' },
  { code: 'CY', es: 'Chipre', en: 'Cyprus' },
  { code: 'CO', es: 'Colombia', en: 'Colombia' },
  { code: 'KM', es: 'Comoras', en: 'Comoros' },
  { code: 'CG', es: 'Congo', en: 'Republic of the Congo' },
  { code: 'CD', es: 'Congo (RD)', en: 'Democratic Republic of the Congo' },
  { code: 'KP', es: 'Corea del Norte', en: 'North Korea' },
  { code: 'KR', es: 'Corea del Sur', en: 'South Korea' },
  { code: 'CI', es: 'Costa de Marfil', en: 'Ivory Coast' },
  { code: 'CR', es: 'Costa Rica', en: 'Costa Rica' },
  { code: 'HR', es: 'Croacia', en: 'Croatia' },
  { code: 'CU', es: 'Cuba', en: 'Cuba' },
  { code: 'DK', es: 'Dinamarca', en: 'Denmark' },
  { code: 'DM', es: 'Dominica', en: 'Dominica' },
  { code: 'EC', es: 'Ecuador', en: 'Ecuador' },
  { code: 'EG', es: 'Egipto', en: 'Egypt' },
  { code: 'SV', es: 'El Salvador', en: 'El Salvador' },
  { code: 'AE', es: 'Emiratos Árabes Unidos', en: 'United Arab Emirates' },
  { code: 'ER', es: 'Eritrea', en: 'Eritrea' },
  { code: 'SK', es: 'Eslovaquia', en: 'Slovakia' },
  { code: 'SI', es: 'Eslovenia', en: 'Slovenia' },
  { code: 'ES', es: 'España', en: 'Spain' },
  { code: 'US', es: 'Estados Unidos', en: 'United States of America' },
  { code: 'EE', es: 'Estonia', en: 'Estonia' },
  { code: 'SZ', es: 'Esuatini', en: 'Eswatini' },
  { code: 'ET', es: 'Etiopía', en: 'Ethiopia' },
  { code: 'PH', es: 'Filipinas', en: 'Philippines' },
  { code: 'FI', es: 'Finlandia', en: 'Finland' },
  { code: 'FJ', es: 'Fiyi', en: 'Fiji' },
  { code: 'FR', es: 'Francia', en: 'France' },
  { code: 'GA', es: 'Gabón', en: 'Gabon' },
  { code: 'GM', es: 'Gambia', en: 'The Gambia' },
  { code: 'GE', es: 'Georgia', en: 'Georgia (country)' },
  { code: 'GH', es: 'Ghana', en: 'Ghana' },
  { code: 'GD', es: 'Granada', en: 'Grenada' },
  { code: 'GR', es: 'Grecia', en: 'Greece' },
  { code: 'GT', es: 'Guatemala', en: 'Guatemala' },
  { code: 'GN', es: 'Guinea', en: 'Guinea' },
  { code: 'GQ', es: 'Guinea Ecuatorial', en: 'Equatorial Guinea' },
  { code: 'GW', es: 'Guinea-Bisáu', en: 'Guinea-Bissau' },
  { code: 'GY', es: 'Guyana', en: 'Guyana' },
  { code: 'HT', es: 'Haití', en: 'Haiti' },
  { code: 'HN', es: 'Honduras', en: 'Honduras' },
  { code: 'HU', es: 'Hungría', en: 'Hungary' },
  { code: 'IN', es: 'India', en: 'India' },
  { code: 'ID', es: 'Indonesia', en: 'Indonesia' },
  { code: 'IQ', es: 'Irak', en: 'Iraq' },
  { code: 'IR', es: 'Irán', en: 'Iran' },
  { code: 'IE', es: 'Irlanda', en: 'Ireland' },
  { code: 'IS', es: 'Islandia', en: 'Iceland' },
  { code: 'IL', es: 'Israel', en: 'Israel' },
  { code: 'IT', es: 'Italia', en: 'Italy' },
  { code: 'JM', es: 'Jamaica', en: 'Jamaica' },
  { code: 'JP', es: 'Japón', en: 'Japan' },
  { code: 'JO', es: 'Jordania', en: 'Jordan' },
  { code: 'KZ', es: 'Kazajistán', en: 'Kazakhstan' },
  { code: 'KE', es: 'Kenia', en: 'Kenya' },
  { code: 'KG', es: 'Kirguistán', en: 'Kyrgyzstan' },
  { code: 'KI', es: 'Kiribati', en: 'Kiribati' },
  { code: 'KW', es: 'Kuwait', en: 'Kuwait' },
  { code: 'LA', es: 'Laos', en: 'Laos' },
  { code: 'LS', es: 'Lesoto', en: 'Lesotho' },
  { code: 'LV', es: 'Letonia', en: 'Latvia' },
  { code: 'LB', es: 'Líbano', en: 'Lebanon' },
  { code: 'LR', es: 'Liberia', en: 'Liberia' },
  { code: 'LY', es: 'Libia', en: 'Libya' },
  { code: 'LI', es: 'Liechtenstein', en: 'Liechtenstein' },
  { code: 'LT', es: 'Lituania', en: 'Lithuania' },
  { code: 'LU', es: 'Luxemburgo', en: 'Luxembourg' },
  { code: 'MK', es: 'Macedonia del Norte', en: 'North Macedonia' },
  { code: 'MG', es: 'Madagascar', en: 'Madagascar' },
  { code: 'MY', es: 'Malasia', en: 'Malaysia' },
  { code: 'MW', es: 'Malaui', en: 'Malawi' },
  { code: 'MV', es: 'Maldivas', en: 'Maldives' },
  { code: 'ML', es: 'Malí', en: 'Mali' },
  { code: 'MT', es: 'Malta', en: 'Malta' },
  { code: 'MA', es: 'Marruecos', en: 'Morocco' },
  { code: 'MU', es: 'Mauricio', en: 'Mauritius' },
  { code: 'MR', es: 'Mauritania', en: 'Mauritania' },
  { code: 'MX', es: 'México', en: 'Mexico' },
  { code: 'FM', es: 'Micronesia', en: 'Federated States of Micronesia' },
  { code: 'MD', es: 'Moldavia', en: 'Moldova' },
  { code: 'MC', es: 'Mónaco', en: 'Monaco' },
  { code: 'MN', es: 'Mongolia', en: 'Mongolia' },
  { code: 'ME', es: 'Montenegro', en: 'Montenegro' },
  { code: 'MZ', es: 'Mozambique', en: 'Mozambique' },
  { code: 'MM', es: 'Myanmar', en: 'Myanmar' },
  { code: 'NA', es: 'Namibia', en: 'Namibia' },
  { code: 'NR', es: 'Nauru', en: 'Nauru' },
  { code: 'NP', es: 'Nepal', en: 'Nepal' },
  { code: 'NI', es: 'Nicaragua', en: 'Nicaragua' },
  { code: 'NE', es: 'Níger', en: 'Niger' },
  { code: 'NG', es: 'Nigeria', en: 'Nigeria' },
  { code: 'NO', es: 'Noruega', en: 'Norway' },
  { code: 'NZ', es: 'Nueva Zelanda', en: 'New Zealand' },
  { code: 'OM', es: 'Omán', en: 'Oman' },
  { code: 'NL', es: 'Países Bajos', en: 'Netherlands' },
  { code: 'PK', es: 'Pakistán', en: 'Pakistan' },
  { code: 'PW', es: 'Palaos', en: 'Palau' },
  { code: 'PS', es: 'Palestina', en: 'Palestinian territories' },
  { code: 'PA', es: 'Panamá', en: 'Panama' },
  { code: 'PG', es: 'Papúa Nueva Guinea', en: 'Papua New Guinea' },
  { code: 'PY', es: 'Paraguay', en: 'Paraguay' },
  { code: 'PE', es: 'Perú', en: 'Peru' },
  { code: 'PL', es: 'Polonia', en: 'Poland' },
  { code: 'PT', es: 'Portugal', en: 'Portugal' },
  { code: 'GB', es: 'Reino Unido', en: 'United Kingdom' },
  { code: 'CF', es: 'República Centroafricana', en: 'Central African Republic' },
  { code: 'CZ', es: 'República Checa', en: 'Czech Republic' },
  { code: 'DO', es: 'República Dominicana', en: 'Dominican Republic' },
  { code: 'RW', es: 'Ruanda', en: 'Rwanda' },
  { code: 'RO', es: 'Rumanía', en: 'Romania' },
  { code: 'RU', es: 'Rusia', en: 'Russia' },
  { code: 'WS', es: 'Samoa', en: 'Samoa' },
  { code: 'KN', es: 'San Cristóbal y Nieves', en: 'Saint Kitts and Nevis' },
  { code: 'SM', es: 'San Marino', en: 'San Marino' },
  { code: 'VC', es: 'San Vicente y las Granadinas', en: 'Saint Vincent and the Grenadines' },
  { code: 'LC', es: 'Santa Lucía', en: 'Saint Lucia' },
  { code: 'ST', es: 'Santo Tomé y Príncipe', en: 'São Tomé and Príncipe' },
  { code: 'SN', es: 'Senegal', en: 'Senegal' },
  { code: 'RS', es: 'Serbia', en: 'Serbia' },
  { code: 'SC', es: 'Seychelles', en: 'Seychelles' },
  { code: 'SL', es: 'Sierra Leona', en: 'Sierra Leone' },
  { code: 'SG', es: 'Singapur', en: 'Singapore' },
  { code: 'SY', es: 'Siria', en: 'Syria' },
  { code: 'SO', es: 'Somalia', en: 'Somalia' },
  { code: 'LK', es: 'Sri Lanka', en: 'Sri Lanka' },
  { code: 'ZA', es: 'Sudáfrica', en: 'South Africa' },
  { code: 'SD', es: 'Sudán', en: 'Sudan' },
  { code: 'SS', es: 'Sudán del Sur', en: 'South Sudan' },
  { code: 'SE', es: 'Suecia', en: 'Sweden' },
  { code: 'CH', es: 'Suiza', en: 'Switzerland' },
  { code: 'SR', es: 'Surinam', en: 'Suriname' },
  { code: 'TH', es: 'Tailandia', en: 'Thailand' },
  { code: 'TW', es: 'Taiwán', en: 'Taiwan' },
  { code: 'TZ', es: 'Tanzania', en: 'Tanzania' },
  { code: 'TJ', es: 'Tayikistán', en: 'Tajikistan' },
  { code: 'TL', es: 'Timor Oriental', en: 'East Timor' },
  { code: 'TG', es: 'Togo', en: 'Togo' },
  { code: 'TO', es: 'Tonga', en: 'Tonga' },
  { code: 'TT', es: 'Trinidad y Tobago', en: 'Trinidad and Tobago' },
  { code: 'TN', es: 'Túnez', en: 'Tunisia' },
  { code: 'TM', es: 'Turkmenistán', en: 'Turkmenistan' },
  { code: 'TR', es: 'Turquía', en: 'Turkey' },
  { code: 'TV', es: 'Tuvalu', en: 'Tuvalu' },
  { code: 'UA', es: 'Ucrania', en: 'Ukraine' },
  { code: 'UG', es: 'Uganda', en: 'Uganda' },
  { code: 'UY', es: 'Uruguay', en: 'Uruguay' },
  { code: 'UZ', es: 'Uzbekistán', en: 'Uzbekistan' },
  { code: 'VU', es: 'Vanuatu', en: 'Vanuatu' },
  { code: 'VA', es: 'Vaticano', en: 'Vatican City' },
  { code: 'VE', es: 'Venezuela', en: 'Venezuela' },
  { code: 'VN', es: 'Vietnam', en: 'Vietnam' },
  { code: 'YE', es: 'Yemen', en: 'Yemen' },
  { code: 'DJ', es: 'Yibuti', en: 'Djibouti' },
  { code: 'ZM', es: 'Zambia', en: 'Zambia' },
  { code: 'ZW', es: 'Zimbabue', en: 'Zimbabwe' },
]

export const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]))

/** Nombre en el idioma activo (leído dentro de un computed es reactivo) */
export function countryName(code: string): string {
  const country = COUNTRY_BY_CODE.get(code)
  if (!country) return code
  return currentLocale() === 'es' ? country.es : country.en
}

export function countryLabel(code: string): string {
  return `${flagEmoji(code)} ${countryName(code)}`
}

/** Opciones ordenadas según el idioma activo; envolver en computed en los consumidores */
export function countryOptions() {
  const locale = intlLocale()
  return COUNTRIES.map((c) => ({
    code: c.code,
    label: countryLabel(c.code),
  })).sort((a, b) => a.label.localeCompare(b.label, locale))
}
